#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /home/cms/git-2.8.1 and test-fake-ssh.

GIT_EXEC_PATH='/home/cms/git-2.8.1'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/home/cms/git-2.8.1/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/home/cms/git-2.8.1/perl/blib/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/home/cms/git-2.8.1/po/build/locale'
PATH='/home/cms/git-2.8.1/bin-wrappers:'"$PATH"
export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

if test -n "$GIT_TEST_GDB"
then
	unset GIT_TEST_GDB
	exec gdb --args "${GIT_EXEC_PATH}/test-fake-ssh" "$@"
else
	exec "${GIT_EXEC_PATH}/test-fake-ssh" "$@"
fi
